@file:OptIn(ExperimentalCoroutinesApi::class)

package com.mikitazayanchkouski.imageskmp.features.listAndDetails.presentation.screens.details.viewModel

import app.cash.turbine.test
import assertk.assertThat
import assertk.assertions.isEqualTo
import assertk.assertions.isFalse
import assertk.assertions.isNotNull
import assertk.assertions.isNull
import assertk.assertions.isTrue
import com.mikitazayanchkouski.imageskmp.core.domain.customResultHandling.CustomResult
import com.mikitazayanchkouski.imageskmp.core.domain.customResultHandling.DataError
import com.mikitazayanchkouski.imageskmp.features.listAndDetails.data.repository.FakeImagesRepository
import com.mikitazayanchkouski.imageskmp.features.listAndDetails.domain.models.ImagesCategories
import com.mikitazayanchkouski.imageskmp.features.listAndDetails.imageDomainModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.UnconfinedTestDispatcher
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import kotlin.test.AfterTest
import kotlin.test.BeforeTest
import kotlin.test.Test

/** These tests were generated by Me,
 * with the help of the Claude Code agent and my existing skill for testing.
 */
class ImageDetailsViewModelTest {

    private val testDispatcher = UnconfinedTestDispatcher()

    @BeforeTest
    fun setUp() {
        Dispatchers.setMain(dispatcher = testDispatcher)
    }

    @AfterTest
    fun tearDown() {
        Dispatchers.resetMain()
    }

    private fun viewModel(
        repository: FakeImagesRepository,
        imageId: Long = IMAGE_ID,
        fromSearch: Boolean = false,
        fromBookmarks: Boolean = false
    ) = ImageDetailsViewModel(
        imagesRepository = repository,
        imageId = imageId,
        areDetailsOpenedFromSearchScreen = fromSearch,
        areDetailsOpenedFromBookmarksScreen = fromBookmarks
    )

    // ---------- Load: bookmarks screen ----------

    @Test
    fun `Loading from bookmarks with a found image marks it loaded and in bookmarks`() = runTest {
        val repository = FakeImagesRepository().apply {
            bookmarkImage = imageDomainModel(
                imageId = IMAGE_ID,
                isInBookmarks = false
            )
        }
        val viewModel = viewModel(
            repository = repository,
            fromBookmarks = true
        )

        viewModel.state.test {
            val state = expectMostRecentItem()
            assertThat(actual = state.isLoading).isFalse()
            assertThat(actual = state.isImageLoadedSuccessfully).isTrue()
            assertThat(actual = state.image?.imageId).isEqualTo(expected = IMAGE_ID)
            // ViewModel forces isInBookmarks = true for bookmark-loaded images.
            assertThat(actual = state.image?.isInBookmarks).isEqualTo(expected = true)
            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun `Loading from bookmarks with no image marks load unsuccessful`() = runTest {
        val repository = FakeImagesRepository().apply { bookmarkImage = null }
        val viewModel = viewModel(
            repository = repository,
            fromBookmarks = true
        )

        viewModel.state.test {
            val state = expectMostRecentItem()
            assertThat(actual = state.isLoading).isFalse()
            assertThat(actual = state.isImageLoadedSuccessfully).isFalse()
            assertThat(actual = state.image).isNull()
            cancelAndIgnoreRemainingEvents()
        }
    }

    // ---------- Load: search screen ----------

    @Test
    fun `Loading from search with a successful result marks it loaded`() = runTest {
        val repository = FakeImagesRepository().apply {
            searchResult = CustomResult.Success(
                data = imageDomainModel(
                    imageId = IMAGE_ID,
                    imageCategory = ImagesCategories.SEARCH
                )
            )
        }
        val viewModel = viewModel(
            repository = repository,
            fromSearch = true
        )

        viewModel.state.test {
            val state = expectMostRecentItem()
            assertThat(actual = state.isLoading).isFalse()
            assertThat(actual = state.isImageLoadedSuccessfully).isTrue()
            assertThat(actual = state.image?.imageId).isEqualTo(expected = IMAGE_ID)
            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun `Loading from search with a failure marks load unsuccessful`() = runTest {
        val repository = FakeImagesRepository().apply {
            searchResult = CustomResult.Failure(error = DataError.Remote.UNKNOWN)
        }
        val viewModel = viewModel(
            repository = repository,
            fromSearch = true
        )

        viewModel.state.test {
            val state = expectMostRecentItem()
            assertThat(actual = state.isLoading).isFalse()
            assertThat(actual = state.isImageLoadedSuccessfully).isFalse()
            cancelAndIgnoreRemainingEvents()
        }
    }

    // ---------- Load: cache (any other screen) ----------

    @Test
    fun `Loading from cache with a found image marks it loaded`() = runTest {
        val repository = FakeImagesRepository().apply {
            cacheImage = imageDomainModel(imageId = IMAGE_ID)
        }
        val viewModel = viewModel(repository = repository)

        viewModel.state.test {
            val state = expectMostRecentItem()
            assertThat(actual = state.isLoading).isFalse()
            assertThat(actual = state.isImageLoadedSuccessfully).isTrue()
            assertThat(actual = state.image?.imageId).isEqualTo(expected = IMAGE_ID)
            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun `Loading from cache with no image marks load unsuccessful`() = runTest {
        val repository = FakeImagesRepository().apply { cacheImage = null }
        val viewModel = viewModel(repository = repository)

        viewModel.state.test {
            val state = expectMostRecentItem()
            assertThat(actual = state.isLoading).isFalse()
            assertThat(actual = state.isImageLoadedSuccessfully).isFalse()
            assertThat(actual = state.image).isNull()
            cancelAndIgnoreRemainingEvents()
        }
    }

    // ---------- Toggle bookmark ----------

    @Test
    fun `toggling a bookmarked SEARCH image deletes it from bookmarks only`() = runTest {
        val repository = FakeImagesRepository().apply {
            searchResult = CustomResult.Success(
                data = imageDomainModel(
                    imageId = IMAGE_ID,
                    imageCategory = ImagesCategories.SEARCH,
                    isInBookmarks = true
                )
            )
        }
        val viewModel = viewModel(
            repository = repository,
            fromSearch = true
        )

        viewModel.state.test {
            assertThat(actual = expectMostRecentItem().image).isNotNull()
            viewModel.onUserAction(ImageDetailsActions.OnSwitchIsInBookmarksState(imageId = IMAGE_ID))
            cancelAndIgnoreRemainingEvents()
        }

        assertThat(actual = repository.deletedFromBookmarksId).isEqualTo(expected = IMAGE_ID)
        assertThat(actual = repository.deletedAndSyncedId).isNull()
    }

    @Test
    fun `Toggling a bookmarked non-SEARCH image deletes it and syncs the cache`() = runTest {
        val repository = FakeImagesRepository().apply {
            cacheImage = imageDomainModel(
                imageId = IMAGE_ID,
                imageCategory = ImagesCategories.NATURE,
                isInBookmarks = true
            )
        }
        val viewModel = viewModel(repository = repository)

        viewModel.state.test {
            assertThat(actual = expectMostRecentItem().image).isNotNull()
            viewModel.onUserAction(ImageDetailsActions.OnSwitchIsInBookmarksState(imageId = IMAGE_ID))
            cancelAndIgnoreRemainingEvents()
        }

        assertThat(actual = repository.deletedAndSyncedId).isEqualTo(expected = IMAGE_ID)
        assertThat(actual = repository.deletedFromBookmarksId).isNull()
    }

    @Test
    fun `toggling a non-bookmarked SEARCH image adds it to bookmarks only`() = runTest {
        val repository = FakeImagesRepository().apply {
            searchResult = CustomResult.Success(
                data = imageDomainModel(
                    imageId = IMAGE_ID,
                    imageCategory = ImagesCategories.SEARCH,
                    isInBookmarks = false
                )
            )
        }
        val viewModel = viewModel(
            repository = repository,
            fromSearch = true
        )

        viewModel.state.test {
            assertThat(actual = expectMostRecentItem().image).isNotNull()
            viewModel.onUserAction(ImageDetailsActions.OnSwitchIsInBookmarksState(imageId = IMAGE_ID))
            cancelAndIgnoreRemainingEvents()
        }

        assertThat(actual = repository.addedToBookmarks?.imageId).isEqualTo(expected = IMAGE_ID)
        // ViewModel marks the image as bookmarked before inserting.
        assertThat(actual = repository.addedToBookmarks?.isInBookmarks).isEqualTo(expected = true)
        assertThat(actual = repository.addedAndSynced).isNull()
    }

    @Test
    fun `toggling a non-bookmarked non-SEARCH image adds it and syncs the cache`() = runTest {
        val repository = FakeImagesRepository().apply {
            cacheImage = imageDomainModel(
                imageId = IMAGE_ID,
                imageCategory = ImagesCategories.NATURE,
                isInBookmarks = false
            )
        }
        val viewModel = viewModel(repository)

        viewModel.state.test {
            assertThat(actual = expectMostRecentItem().image).isNotNull()
            viewModel.onUserAction(ImageDetailsActions.OnSwitchIsInBookmarksState(imageId = IMAGE_ID))
            cancelAndIgnoreRemainingEvents()
        }

        assertThat(actual = repository.addedAndSynced?.imageId).isEqualTo(expected = IMAGE_ID)
        assertThat(actual = repository.addedToBookmarks).isNull()
    }

    private companion object {
        const val IMAGE_ID = 1L
    }
}
